export type Lang = "en" | "de" | "pt";

export type Tag = "vegan" | "vegetarian" | "glutenfree" | "lactosefree" | "spicy" | "chef" | "new";

export interface MenuItem {
  id: string;
  category: string;
  price: number;
  image?: string;
  allergens: string[];
  tags: Tag[];
  popular?: boolean;
  available?: boolean;
  name: Record<Lang, string>;
  desc: Record<Lang, string>;
}

export interface Category {
  id: string;
  name: Record<Lang, string>;
}

const IMG = "/menu/";

export const categories: Category[] = [
  { id: "appetizers", name: { en: "Starters", de: "Vorspeisen", pt: "Entradas" } },
  { id: "quesadillas", name: { en: "Quesadillas", de: "Quesadillas", pt: "Quesadillas" } },
  { id: "tacos", name: { en: "Tacos", de: "Tacos", pt: "Tacos" } },
  { id: "bowls", name: { en: "Bowls", de: "Bowls", pt: "Bowls" } },
  { id: "mains", name: { en: "Soul Food Mains", de: "Pratos Feitos", pt: "Pratos Feitos" } },
  { id: "seafood", name: { en: "Seafood", de: "Meeresfrüchte", pt: "Pratos do Mar" } },
  { id: "sides", name: { en: "Sides", de: "Beilagen", pt: "Acompanhamentos" } },
  { id: "drinks", name: { en: "Drinks & Cocktails", de: "Getränke & Cocktails", pt: "Bebidas" } },
  { id: "desserts", name: { en: "Desserts", de: "Desserts", pt: "Sobremesas" } },
];

export const allergenKey: Record<string, Record<Lang, string>> = {
  A: { en: "Cereals containing gluten", de: "Glutenhaltiges Getreide", pt: "Cereais com glúten" },
  M: { en: "Milk / lactose", de: "Milch / Laktose", pt: "Leite / lactose" },
  G: { en: "Milk / lactose", de: "Milch / Laktose", pt: "Leite / lactose" },
  B: { en: "Crustaceans", de: "Krebstiere", pt: "Crustáceos" },
  R: { en: "Molluscs", de: "Weichtiere", pt: "Moluscos" },
  E: { en: "Peanuts", de: "Erdnüsse", pt: "Amendoim" },
  F: { en: "Soy", de: "Soja", pt: "Soja" },
};

export const menuItems: MenuItem[] = [
  {
    id: "nachos",
    category: "appetizers",
    price: 8.9,
    image: IMG + "nachos-guac.webp",
    allergens: [],
    tags: ["vegetarian"],
    name: { en: "Nachos with Guacamole", de: "Nachos mit Guacamole", pt: "Nachos com Guacamole" },
    desc: {
      en: "Crispy corn chips served with fresh guacamole.",
      de: "Knusprige Maischips, serviert mit Guacamole.",
      pt: "Chips de milho crocantes servidos com guacamole.",
    },
  },
  {
    id: "ceviche",
    category: "appetizers",
    price: 8.9,
    allergens: [],
    tags: ["vegan", "glutenfree"],
    name: { en: "Mango Ceviche", de: "Mango Ceviche", pt: "Ceviche de Manga" },
    desc: {
      en: "Fresh mango with tomato, onion and crunchy corn.",
      de: "Frische Mango mit Tomaten, Zwiebeln und Knusper-Mais.",
      pt: "Manga fresca com tomate, cebola e milho crocante.",
    },
  },
  {
    id: "coxinha",
    category: "appetizers",
    price: 8.9,
    image: IMG + "coxinha.webp",
    allergens: ["A", "M"],
    tags: [],
    name: { en: "Coxinha with Salad", de: "Coxinha mit Salat", pt: "Coxinha com Salada" },
    desc: {
      en: "Brazilian dough pockets filled with chicken, served with salad.",
      de: "Brasilianische Teigtasche mit Hühnerfleischfüllung, serviert mit Salat.",
      pt: "Salgado brasileiro recheado com frango, servido com salada.",
    },
  },
  {
    id: "pao-de-queijo",
    category: "appetizers",
    price: 10.9,
    image: IMG + "pao-de-queijo.webp",
    allergens: ["M"],
    tags: ["vegetarian", "glutenfree"],
    name: { en: "Pão de Queijo", de: "Pão de Queijo", pt: "Pão de Queijo" },
    desc: {
      en: "Freshly baked Brazilian cheese bread balls.",
      de: "Frische brasilianische Käsebällchen, frisch gebacken.",
      pt: "Pãezinhos de queijo brasileiros assados na hora.",
    },
  },

  {
    id: "quesadilla-pollo",
    category: "quesadillas",
    price: 15.0,
    image: IMG + "quesadilla-haehnchen.webp",
    allergens: ["A", "G"],
    tags: [],
    name: { en: "Chicken Quesadilla", de: "Hähnchen (Pollo) Quesadilla", pt: "Quesadilla de Frango" },
    desc: { en: "With melted Gouda.", de: "Mit geschmolzenem Gouda.", pt: "Com gouda derretido." },
  },
  {
    id: "quesadilla-cerdo",
    category: "quesadillas",
    price: 15.0,
    allergens: ["A", "G"],
    tags: [],
    name: { en: "Pork Quesadilla", de: "Schwein (Cerdo) Quesadilla", pt: "Quesadilla de Porco" },
    desc: {
      en: "With pizza cheese (mozzarella mix).",
      de: "Mit Pizzakäse (Mozzarella-Mix).",
      pt: "Com mistura de mozzarella.",
    },
  },
  {
    id: "quesadilla-veg",
    category: "quesadillas",
    price: 13.9,
    allergens: ["A", "G"],
    tags: ["vegetarian"],
    name: { en: "Vegetarian Quesadilla", de: "Vegetarische Quesadilla", pt: "Quesadilla Vegetariana" },
    desc: {
      en: "Spinach, feta and Austrian cheese (Gouda & mozzarella).",
      de: "Mit Spinat, Feta & österreichischem Käse (Gouda & Mozzarella).",
      pt: "Espinafre, feta e queijo austríaco.",
    },
  },
  {
    id: "quesadilla-summer",
    category: "quesadillas",
    price: 14.9,
    allergens: ["A", "G"],
    tags: ["vegetarian"],
    name: { en: "Summer Quesadilla", de: "Sommer Quesadilla", pt: "Quesadilla de Verão" },
    desc: { en: "Cheese and pico de gallo.", de: "Mit Käse & Pico de Gallo.", pt: "Queijo e pico de gallo." },
  },

  {
    id: "taco-especial",
    category: "tacos",
    price: 18.9,
    image: IMG + "taco-especial.webp",
    allergens: ["A", "M"],
    tags: ["chef"],
    popular: true,
    name: { en: "Taco Especial", de: "Taco Especial", pt: "Taco Especial" },
    desc: {
      en: "Grilled picanha beef, black beans, salad, pico de gallo, guacamole.",
      de: "Gegrilltes Rindfleisch (Picanha), schwarze Bohnen, Salat, Pico de Gallo, Guacamole.",
      pt: "Picanha grelhada, feijão preto, salada, pico de gallo, guacamole.",
    },
  },
  {
    id: "taco-pollo",
    category: "tacos",
    price: 15.9,
    image: IMG + "chicken-taco.webp",
    allergens: ["A", "M"],
    tags: [],
    name: { en: "Taco Pollo", de: "Taco Pollo", pt: "Taco Pollo" },
    desc: {
      en: "Slow-cooked chicken, salad, pico de gallo, guacamole.",
      de: "Langsam gegartes Hähnchen, Salat, Pico de Gallo, Guacamole.",
      pt: "Frango cozido lentamente, salada, pico de gallo, guacamole.",
    },
  },
  {
    id: "taco-vegano",
    category: "tacos",
    price: 13.9,
    image: IMG + "veggie-taco.webp",
    allergens: ["A", "M"],
    tags: ["vegan", "glutenfree"],
    name: { en: "Taco Vegano", de: "Taco Vegano", pt: "Taco Vegano" },
    desc: {
      en: "Soy protein with Brazilian spices, salad, pico de gallo, guacamole.",
      de: "Sojaprotein mit brasilianischen Gewürzen, Salat, Pico de Gallo, Guacamole.",
      pt: "Proteína de soja com temperos brasileiros, salada, pico de gallo, guacamole.",
    },
  },
  {
    id: "taco-pulled-pork",
    category: "tacos",
    price: 16.9,
    allergens: ["A"],
    tags: [],
    name: { en: "Taco Pulled Pork", de: "Taco Pulled Pork", pt: "Taco Pulled Pork" },
    desc: {
      en: "Pulled pork, salad, pico de gallo, guacamole.",
      de: "Gezupftes Schweinefleisch, Salat, Pico de Gallo, Guacamole.",
      pt: "Porco desfiado, salada, pico de gallo, guacamole.",
    },
  },
  {
    id: "taco-res",
    category: "tacos",
    price: 17.99,
    image: IMG + "beef-taco.webp",
    allergens: ["A", "M"],
    tags: [],
    popular: true,
    name: { en: "Taco Res", de: "Taco Res", pt: "Taco Res" },
    desc: {
      en: "Slow-cooked beef, salad, pico de gallo, guacamole.",
      de: "Langsam gekochtes Rindfleisch, Salat, Pico de Gallo, Guacamole.",
      pt: "Carne cozida lentamente, salada, pico de gallo, guacamole.",
    },
  },
  {
    id: "taco-gambas",
    category: "tacos",
    price: 18.9,
    allergens: ["A", "B", "M"],
    tags: ["glutenfree"],
    name: { en: "Taco Gambas", de: "Taco Gambas", pt: "Taco de Camarão" },
    desc: {
      en: "Prawns, salad, pico de gallo, guacamole.",
      de: "Garnelen, Salat, Pico de Gallo, Guacamole.",
      pt: "Camarões, salada, pico de gallo, guacamole.",
    },
  },

  {
    id: "veggie-bowl",
    category: "bowls",
    price: 14.9,
    image: IMG + "veggie-bowl.webp",
    allergens: ["A", "F"],
    tags: ["vegan", "glutenfree"],
    name: { en: "Veggie Bowl", de: "Veggie Bowl", pt: "Veggie Bowl" },
    desc: {
      en: "Rice, black beans, Brazilian-style soy protein, corn, salad, pico de gallo, guacamole.",
      de: "Reis, schwarze Bohnen, Sojaprotein nach brasilianischer Art, Mais, Salat, Pico de Gallo, Guacamole.",
      pt: "Arroz, feijão preto, proteína de soja, milho, salada, pico de gallo, guacamole.",
    },
  },
  {
    id: "latino-bowl",
    category: "bowls",
    price: 15.9,
    allergens: ["A"],
    tags: ["glutenfree"],
    name: { en: "Latino Bowl", de: "Latino Bowl", pt: "Latino Bowl" },
    desc: {
      en: "Rice, black beans, chicken, salad, pico de gallo, guacamole.",
      de: "Reis, schwarze Bohnen, Hähnchenfleisch, Salat, Pico de Gallo, Guacamole.",
      pt: "Arroz, feijão preto, frango, salada, pico de gallo, guacamole.",
    },
  },
  {
    id: "beef-bowl",
    category: "bowls",
    price: 16.9,
    image: IMG + "beef-bowl.webp",
    allergens: ["A"],
    tags: ["glutenfree", "chef"],
    popular: true,
    name: { en: "Brazil Beef Bowl", de: "Brazil Beef Bowl", pt: "Brazil Beef Bowl" },
    desc: {
      en: "Rice, black beans, tender beef, salad, pico de gallo, guacamole.",
      de: "Reis, schwarze Bohnen, Rindfleisch, Salat, Pico de Gallo, Guacamole.",
      pt: "Arroz, feijão preto, carne, salada, pico de gallo, guacamole.",
    },
  },
  {
    id: "texmex-bowl",
    category: "bowls",
    price: 15.9,
    allergens: ["A"],
    tags: [],
    name: { en: "Tex-Mex Bowl", de: "Tex-Mex Bowl", pt: "Tex-Mex Bowl" },
    desc: {
      en: "Rice, black beans, pork, corn, pico de gallo, guacamole.",
      de: "Reis, schwarze Bohnen, Schweinefleisch, Mais, Pico de Gallo, Guacamole.",
      pt: "Arroz, feijão preto, porco, milho, pico de gallo, guacamole.",
    },
  },
  {
    id: "chipotle-bowl",
    category: "bowls",
    price: 17.9,
    allergens: ["A", "G"],
    tags: ["spicy", "new"],
    name: { en: "Chipotle Bowl", de: "Chipotle Bowl", pt: "Chipotle Bowl" },
    desc: {
      en: "Rice, pinto beans, chicken, salad, guacamole, cheese, sour cream.",
      de: "Reis, Pinto Bohnen, Hähnchen, Salat, Guacamole, Käse, Sauerrahm.",
      pt: "Arroz, feijão pinto, frango, salada, guacamole, queijo, creme azedo.",
    },
  },
  {
    id: "surf-turf-bowl",
    category: "bowls",
    price: 18.9,
    allergens: ["A", "B"],
    tags: ["glutenfree", "new"],
    name: { en: "Surf & Turf Bowl", de: "Surf & Turf Bowl", pt: "Surf & Turf Bowl" },
    desc: {
      en: "Rice, black beans, beef and prawns, salad, guacamole.",
      de: "Reis, schwarze Bohnen, Rindfleisch & Garnelen, Salat, Guacamole.",
      pt: "Arroz, feijão preto, carne e camarões, salada, guacamole.",
    },
  },

  {
    id: "feijoada",
    category: "mains",
    price: 18.9,
    image: IMG + "feijoada.webp",
    allergens: [],
    tags: ["glutenfree", "chef"],
    popular: true,
    name: { en: "Feijoada", de: "Feijoada", pt: "Feijoada" },
    desc: {
      en: "Traditional Brazilian black bean stew with beef, sausage and pork, served with salad.",
      de: "Traditioneller brasilianischer Bohneneintopf mit Rindfleisch, Wurst und Schweinefleisch, serviert mit Salat.",
      pt: "Feijoada tradicional com carne, linguiça e porco, servida com salada.",
    },
  },
  {
    id: "picanha",
    category: "mains",
    price: 22.9,
    image: IMG + "picanha.webp",
    allergens: [],
    tags: ["glutenfree"],
    popular: true,
    name: { en: "Picanha", de: "Picanha", pt: "Picanha" },
    desc: {
      en: "Grilled Brazilian picanha served with rice, salad and farofa.",
      de: "Brasilianische Picanha vom Grill, serviert mit Reis, Salat und Farofa.",
      pt: "Picanha brasileira na grelha, servida com arroz, salada e farofa.",
    },
  },
  {
    id: "african-stew",
    category: "mains",
    price: 17.9,
    image: IMG + "african-stew.webp",
    allergens: ["E"],
    tags: ["glutenfree", "lactosefree"],
    name: { en: "African Peanut Stew with Fufu", de: "African Peanut Stew mit Fufu", pt: "Ensopado Africano de Amendoim com Fufu" },
    desc: {
      en: "Creamy peanut stew with chicken and vegetables, served with fufu and plantain.",
      de: "Cremiger Erdnusseintopf mit Hähnchen und Gemüse, serviert mit Fufu und Kochbananen.",
      pt: "Ensopado cremoso de amendoim com frango e legumes, servido com fufu e banana.",
    },
  },
  {
    id: "veggie-stew",
    category: "mains",
    price: 16.9,
    image: IMG + "fufu.webp",
    allergens: ["E"],
    tags: ["vegan", "glutenfree", "lactosefree"],
    name: { en: "Veggie Peanut Stew with Fufu", de: "Veggie Peanut Stew mit Fufu", pt: "Ensopado Vegano de Amendoim com Fufu" },
    desc: {
      en: "Creamy vegetarian peanut stew with vegetables, served with fufu.",
      de: "Cremiger vegetarischer Erdnusseintopf mit Gemüse, serviert mit Fufu.",
      pt: "Ensopado vegetariano cremoso de amendoim com legumes, servido com fufu.",
    },
  },
  {
    id: "jollof",
    category: "mains",
    price: 15.9,
    allergens: [],
    tags: ["vegan", "glutenfree", "spicy"],
    name: { en: "Jollof Rice", de: "Jollof Reis", pt: "Arroz Jollof" },
    desc: {
      en: "Spiced jollof rice with vegetables, served with salad. Add chicken +€3,00.",
      de: "Würziger Jollof Reis mit Gemüse, serviert mit Salat. + Frango (Chicken) € 3,00.",
      pt: "Arroz jollof apimentado com legumes, servido com salada. + frango € 3,00.",
    },
  },

  {
    id: "paella",
    category: "seafood",
    price: 23.9,
    image: IMG + "paella-douro.webp",
    allergens: ["B", "R"],
    tags: ["glutenfree", "chef"],
    popular: true,
    name: { en: "Paella D'Ouro", de: "Paella D'Ouro", pt: "Paella D'Ouro" },
    desc: {
      en: "Traditional paella with prawns, mussels and seafood in saffron rice with Mediterranean spices.",
      de: "Traditionelle Paella mit Garnelen, Muscheln und Meeresfrüchten, zubereitet mit Safranreis und mediterranen Gewürzen.",
      pt: "Paella tradicional com camarões, mexilhões e frutos do mar em arroz de açafrão.",
    },
  },
  {
    id: "brisa-do-mar",
    category: "seafood",
    price: 20.9,
    image: IMG + "brisa-do-mar.webp",
    allergens: ["R"],
    tags: [],
    name: { en: "Brisa Do Mar Premium", de: "Brisa Do Mar Premium", pt: "Brisa Do Mar Premium" },
    desc: {
      en: "Mussels and clams in a herbed tomato and white wine sauce.",
      de: "Auswahl aus Miesmuscheln und Venusmuscheln in einer Tomatensauce mit Kräutern und Weißwein.",
      pt: "Mexilhões e amêijoas em molho de tomate com ervas e vinho branco.",
    },
  },

  {
    id: "sweet-potato-fries",
    category: "sides",
    price: 8.9,
    allergens: [],
    tags: ["vegan", "glutenfree"],
    name: { en: "Sweet Potato Fries", de: "Süsskartoffel-Pommes", pt: "Batata Doce Frita" },
    desc: {
      en: "Crispy sweet potato fries with sea salt and house aioli dip.",
      de: "Knusprige Pommes aus Süsskartoffeln mit Meersalz und hausgemachtem Aioli-Dip.",
      pt: "Batata doce crocante com sal marinho e aioli da casa.",
    },
  },

  {
    id: "amazonas",
    category: "drinks",
    price: 4.9,
    image: IMG + "amazonas.webp",
    allergens: [],
    tags: ["vegan"],
    name: { en: "Amazonas", de: "Amazonas", pt: "Amazonas" },
    desc: {
      en: "Refreshing água fresca with pineapple, mint and coconut water.",
      de: "Erfrischende Água Fresca mit Ananas, Minze und Kokoswasser.",
      pt: "Água fresca de abacaxi, hortelã e água de coco.",
    },
  },
  {
    id: "roja",
    category: "drinks",
    price: 4.9,
    image: IMG + "roja.webp",
    allergens: [],
    tags: ["vegan"],
    name: { en: "Roja", de: "Roja", pt: "Roja" },
    desc: {
      en: "Fruity água fresca with hibiscus, lime and a touch of ginger.",
      de: "Fruchtige Água Fresca mit Hibiskus, Limette und einem Hauch Ingwer.",
      pt: "Água fresca de hibisco, limão e um toque de gengibre.",
    },
  },
  {
    id: "caipirinha",
    category: "drinks",
    price: 8.9,
    image: IMG + "caipirinha.webp",
    allergens: [],
    tags: ["chef"],
    popular: true,
    name: { en: "Caipirinha", de: "Caipirinha", pt: "Caipirinha" },
    desc: {
      en: "Brazil's national cocktail — cachaça, fresh lime, sugar and ice.",
      de: "Brasiliens Nationalcocktail — Cachaça, frische Limette, Zucker und Eis.",
      pt: "O coquetel nacional do Brasil — cachaça, limão, açúcar e gelo.",
    },
  },
  {
    id: "caipirinha-0",
    category: "drinks",
    price: 6.9,
    allergens: [],
    tags: [],
    name: { en: "Caipirinha (alcohol-free)", de: "Caipirinha (alkoholfrei)", pt: "Caipirinha (sem álcool)" },
    desc: {
      en: "Alcohol-free version with lime, sugar and ice.",
      de: "Cachaça-freie Variante mit Limette, Zucker und Eis.",
      pt: "Versão sem álcool com limão, açúcar e gelo.",
    },
  },
  {
    id: "mojito",
    category: "drinks",
    price: 8.9,
    allergens: [],
    tags: [],
    name: { en: "Mojito", de: "Mojito", pt: "Mojito" },
    desc: {
      en: "The Cuban classic — white rum, mint, lime, cane sugar and soda.",
      de: "Der kubanische Klassiker — weißer Rum, frische Minze, Limette, Rohrzucker und Soda.",
      pt: "O clássico cubano — rum branco, hortelã, limão, açúcar e soda.",
    },
  },
  {
    id: "mojito-0",
    category: "drinks",
    price: 6.9,
    allergens: [],
    tags: [],
    name: { en: "Mojito (alcohol-free)", de: "Mojito (alkoholfrei)", pt: "Mojito (sem álcool)" },
    desc: {
      en: "Fresh mint, lime, cane sugar and soda.",
      de: "Frische Minze, Limette, Rohrzucker und Soda.",
      pt: "Hortelã fresca, limão, açúcar de cana e soda.",
    },
  },
  {
    id: "cocktail-rio",
    category: "drinks",
    price: 6.9,
    allergens: [],
    tags: [],
    name: { en: "Cocktail Rio", de: "Cocktail Rio", pt: "Cocktail Rio" },
    desc: {
      en: "Tropical mix of cachaça, passion fruit, lime and coconut cream.",
      de: "Tropischer Mix aus Cachaça, Maracuja, Limette und Kokoscreme.",
      pt: "Mistura tropical de cachaça, maracujá, limão e creme de coco.",
    },
  },
  {
    id: "guarana",
    category: "drinks",
    price: 5.9,
    allergens: [],
    tags: [],
    name: { en: "Guaraná Antarctica", de: "Guaraná Antarctica", pt: "Guaraná Antarctica" },
    desc: {
      en: "Brazil's favourite soft drink with the unique Amazonian guaraná flavour.",
      de: "Brasiliens beliebtestes Erfrischungsgetränk mit Guaraná-Geschmack aus dem Amazonas.",
      pt: "O refrigerante preferido do Brasil, com sabor único de guaraná.",
    },
  },
  {
    id: "softdrinks",
    category: "drinks",
    price: 3.8,
    allergens: [],
    tags: [],
    name: { en: "Soft Drinks", de: "Softdrinks", pt: "Refrigerantes" },
    desc: {
      en: "Sinalco Cola, Fanta, Sprite.",
      de: "Sinalco Cola, Fanta, Sprite.",
      pt: "Sinalco Cola, Fanta, Sprite.",
    },
  },
  {
    id: "water",
    category: "drinks",
    price: 3.2,
    allergens: [],
    tags: [],
    name: { en: "Mineral Water", de: "Mineralwasser", pt: "Água Mineral" },
    desc: {
      en: "Still or sparkling.",
      de: "Mit oder ohne Kohlensäure.",
      pt: "Com ou sem gás.",
    },
  },
  {
    id: "tap-water",
    category: "drinks",
    price: 1.0,
    allergens: [],
    tags: [],
    name: { en: "Tap Water", de: "Leitungswasser", pt: "Água da Torneira" },
    desc: {
      en: "Chilled tap water — refreshing and sustainable.",
      de: "Gekühltes Leitungswasser — erfrischend und umweltbewusst.",
      pt: "Água da torneira gelada — refrescante e sustentável.",
    },
  },
  {
    id: "espresso",
    category: "drinks",
    price: 3.2,
    allergens: [],
    tags: [],
    name: { en: "Café Expresso", de: "Café Expresso", pt: "Café Expresso" },
    desc: {
      en: "Strong Brazilian espresso — intense and aromatic.",
      de: "Kräftiger brasilianischer Espresso — intensiv und aromatisch.",
      pt: "Café expresso brasileiro — intenso e aromático.",
    },
  },
  {
    id: "cafe-gelenga",
    category: "drinks",
    price: 3.8,
    allergens: ["M"],
    tags: [],
    name: { en: "Café Gelenga", de: "Café Gelenga", pt: "Café Gelenga" },
    desc: {
      en: "Brazilian iced coffee with milk foam and a hint of cinnamon.",
      de: "Brasilianischer Eiskaffee mit Milchschaum und einem Hauch Zimt.",
      pt: "Café gelado brasileiro com espuma de leite e canela.",
    },
  },

  {
    id: "pudim",
    category: "desserts",
    price: 4.9,
    image: IMG + "pudimdecaremilo.webp",
    allergens: ["M"],
    tags: ["vegetarian", "chef"],
    popular: true,
    name: { en: "Pudim de Caramelo", de: "Pudim de Caramelo", pt: "Pudim de Caramelo" },
    desc: {
      en: "Silky Brazilian caramel flan with golden caramel sauce.",
      de: "Brasilianischer Karamellpudding — samtig-weich mit goldener Karamellsauce.",
      pt: "Pudim de caramelo brasileiro, sedoso e com calda dourada.",
    },
  },
  {
    id: "torta-chocolate",
    category: "desserts",
    price: 5.9,
    image: IMG + "tortadechocolate.webp",
    allergens: ["A", "M"],
    tags: ["vegetarian"],
    name: { en: "Torta de Chocolate", de: "Torta de Chocolate", pt: "Torta de Chocolate" },
    desc: {
      en: "Moist Brazilian chocolate cake with intense cocoa flavour.",
      de: "Saftiger brasilianischer Schokoladenkuchen mit intensivem Kakaogeschmack.",
      pt: "Bolo de chocolate brasileiro, úmido e intenso.",
    },
  },
  {
    id: "brigadeiro",
    category: "desserts",
    price: 4.9,
    image: IMG + "brigadeiro.webp",
    allergens: ["M"],
    tags: ["vegetarian"],
    name: { en: "Brigadeiro", de: "Brigadeiro", pt: "Brigadeiro" },
    desc: {
      en: "Brazilian chocolate truffles rolled in chocolate sprinkles.",
      de: "Brasilianische Schokoladentrüffel, gerollt in Schokoladenstreuseln.",
      pt: "Trufas brasileiras de chocolate com granulado.",
    },
  },
  {
    id: "beijinho",
    category: "desserts",
    price: 4.9,
    image: IMG + "beijinho.webp",
    allergens: ["M"],
    tags: ["vegetarian"],
    name: { en: "Beijinho", de: "Beijinho", pt: "Beijinho" },
    desc: {
      en: "Brazilian coconut truffles — sweet, tender and delicious.",
      de: "Brasilianische Kokostrüffel — süß, zart und köstlich.",
      pt: "Beijinhos de coco — doces e delicados.",
    },
  },
];

export const restaurant = {
  name: "D'ouro Soul Food",
  tagline: { en: "Afro-Latin Soul Food", de: "Afro-Latin Soulfood", pt: "Soul Food Afro-Latino" },
  street: "Auerspergstraße 10",
  city: "5020 Salzburg, Austria",
  phone: "+43 676 4231921",
  phoneHref: "tel:+436764231921",
  whatsapp: "https://wa.me/436764231921",
  email: "info@douro-soulfood.com",
  maps: "https://www.google.com/maps/search/?api=1&query=Auerspergstra%C3%9Fe+10%2C+5020+Salzburg%2C+Austria",
  googleReview: "https://search.google.com/local/writereview?placeid=ChIJ-3-y_Uvld0gRdfRkL6n3s2M",
  instagram: "https://www.instagram.com/douro_soulfood/",
  facebook: "https://www.facebook.com/people/Douro-Soulfood/61553206676357/",
  tripadvisor:
    "https://www.tripadvisor.com/Restaurant_Review-g190441-d25104877-Reviews-D_ouro_Soulfood_Bistro-Salzburg_Austrian_Alps.html",
  order: "https://www.lieferando.at/en/menu/douro",
  rating: 4.8,
  reviewCount: 978,
  hours: { en: "Mon – Sat · 11:00 – 20:00", de: "Mo – Sa · 11:00 – 20:00", pt: "Seg – Sáb · 11:00 – 20:00" },
};

export const reviews = [
  {
    quote: {
      en: "The best Afro-Latin food in Salzburg! The beef tacos and the caipirinha are world class. Angela is incredibly warm.",
      de: "Das beste Afro-Latin Food in Salzburg! Die Beef Tacos und die Caipirinha sind einfach weltklasse. Angela ist extrem herzlich.",
      pt: "A melhor comida afro-latina de Salzburgo! Os tacos de carne e a caipirinha são de outro nível.",
    },
    author: "Lukas M.",
    source: "Google",
  },
  {
    quote: {
      en: "Angela's food is full of flavour and cooked with love. The fufu took me right back to West Africa. An absolute gem.",
      de: "Angelas Essen ist voller Geschmack und mit Liebe gekocht. Das Fufu hat mich direkt nach Westafrika versetzt. Ein Juwel!",
      pt: "A comida da Angela é cheia de sabor e feita com amor. O fufu me levou direto para a África Ocidental.",
    },
    author: "Amara K.",
    source: "TripAdvisor",
  },
  {
    quote: {
      en: "We booked the catering for a company party and everyone was thrilled. Incredibly tasty food and great service!",
      de: "Wir haben das Catering für eine Firmenfeier gebucht und alle waren restlos begeistert. Unglaublich leckeres Essen und toller Service!",
      pt: "Contratamos o catering para uma festa da empresa e todos adoraram. Comida deliciosa e ótimo serviço!",
    },
    author: "Sophie B.",
    source: "Google",
  },
];
